### ISSUE TITLE
npm version needs to be updated?

### ISSUE THREAD

**Issue by foucist** [jhessin/generator-coffee-mithril#1]
I came across this and attempted to install it following your readme instructions.

It installed "generator-coffee-mithril@1.2.1"

It immediately complained about missing .config/yarn/global/node_modules/generator-coffee-mithril/generators/app/templates/.gitignore

I fixed it by replacing my node_modules/generator-coffee-mithril/ with what is actually in the current master branch.

--
nice project btw, I was mainly curious about coffeescript in conjunction with mithril, I also like your directory structure.  good starter app.  :)

**Comment by jhessin** [comment]
I just pushed to npm. Thanks for letting me know.
